---
os:
  - linux

language: c

node_js:
  - "5.10.1"

env:
  - export NODE_VERSION="5.10.1"

addons:
  apt:
    packages:
      - libgc-dev
      - libgmp-dev

before_install:
  - date
  - export PATSHOME=${HOME}/ATS2
  - export PATH=${PATH}:${PATSHOME}/bin
  - export XATS2JS0=${TRAVIS_BUILD_DIR}
  - export XATSHOME=${XATS2JS0}/xanadu/.
  - export GCC=gcc
  - export CLANG=clang

install:
  - ${XATS2JS0}/travis-ci/install-ats2.sh 0.4.2

after_install:
  - date

before_script:
  - date

script:
  # Building ATS2
  - cd ${PATSHOME}
  - ./configure&&make CC=${GCC} all
  # Building Xanadu
  - cd ${XATS2JS0}
  - (sh ./build.sh)
  - (cd srcgen/TEST && time make > output)

after_script:
  - date
