---
os:
  - linux

language: c

node_js:
  - "5.10.1"

env:
  - export NODE_VERSION="5.10.1"

addons:
  apt:
    packages:
      - libgc-dev
      - libgmp-dev

before_install:
  - date
  - export PATSHOME=${HOME}/ATS2
  - export PATH=${PATH}:${PATSHOME}/bin
  - export XATS2JSD=${TRAVIS_BUILD_DIR}
  - export XATSHOME=${XATS2JSD}/xatsopt/.
  - export GCC=gcc
  - export CLANG=clang

install:
  - ${XATS2JSD}/travis-ci/install-ats2.sh 0.4.2

after_install:
  - date

before_script:
  - date

script:
  # which node
  # Building ATS2
  - cd ${PATSHOME}
  - ./configure&&make CC=${GCC} all
  # Building Xats2js
  - cd ${XATS2JSD}
  - (sh ./build.sh)
  - (cd srcgen/TEST && time make -f Makefile_test)
  # Regression Testing
  - (cd docgen/P-Ground && time make -f Makefile_test)

after_script:
  - date
