############

XJSHOME =\
"./../../../../../../.."

XATS2JS =\
"$(XJSHOME)/bin/xats2js"

############

midterm:: ; \
$(XATS2JS) -d ./midterm.dats

############
midterm_type0:: ; \
$(XATS2JS) -d ./midterm_type0.dats
############
midterm_t0erm:: ; \
$(XATS2JS) -d ./midterm_t0erm.dats
############
midterm_s0env:: ; \
$(XATS2JS) -d ./midterm_s0env.dats
############
midterm_d0env:: ; \
$(XATS2JS) -d ./midterm_d0env.dats
############
midterm_interp:: ; \
$(XATS2JS) -d ./midterm_interp.dats
############

############ end of [Makefile] ############
